// Starter content seeded after onboarding.

export const BLIND_75: Array<{ title: string; topic: string; difficulty: string; url: string; platform: string }> = [
  // Array
  { title: "Two Sum", topic: "Array", difficulty: "Easy", url: "https://leetcode.com/problems/two-sum/", platform: "LeetCode" },
  { title: "Best Time to Buy and Sell Stock", topic: "Array", difficulty: "Easy", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", platform: "LeetCode" },
  { title: "Contains Duplicate", topic: "Array", difficulty: "Easy", url: "https://leetcode.com/problems/contains-duplicate/", platform: "LeetCode" },
  { title: "Product of Array Except Self", topic: "Array", difficulty: "Medium", url: "https://leetcode.com/problems/product-of-array-except-self/", platform: "LeetCode" },
  { title: "Maximum Subarray", topic: "Array", difficulty: "Medium", url: "https://leetcode.com/problems/maximum-subarray/", platform: "LeetCode" },
  { title: "Maximum Product Subarray", topic: "Array", difficulty: "Medium", url: "https://leetcode.com/problems/maximum-product-subarray/", platform: "LeetCode" },
  { title: "Find Minimum in Rotated Sorted Array", topic: "Array", difficulty: "Medium", url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", platform: "LeetCode" },
  { title: "Search in Rotated Sorted Array", topic: "Array", difficulty: "Medium", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", platform: "LeetCode" },
  { title: "3Sum", topic: "Array", difficulty: "Medium", url: "https://leetcode.com/problems/3sum/", platform: "LeetCode" },
  { title: "Container With Most Water", topic: "Array", difficulty: "Medium", url: "https://leetcode.com/problems/container-with-most-water/", platform: "LeetCode" },
  // Binary
  { title: "Sum of Two Integers", topic: "Binary", difficulty: "Medium", url: "https://leetcode.com/problems/sum-of-two-integers/", platform: "LeetCode" },
  { title: "Number of 1 Bits", topic: "Binary", difficulty: "Easy", url: "https://leetcode.com/problems/number-of-1-bits/", platform: "LeetCode" },
  { title: "Counting Bits", topic: "Binary", difficulty: "Easy", url: "https://leetcode.com/problems/counting-bits/", platform: "LeetCode" },
  { title: "Missing Number", topic: "Binary", difficulty: "Easy", url: "https://leetcode.com/problems/missing-number/", platform: "LeetCode" },
  { title: "Reverse Bits", topic: "Binary", difficulty: "Easy", url: "https://leetcode.com/problems/reverse-bits/", platform: "LeetCode" },
  // DP
  { title: "Climbing Stairs", topic: "DP", difficulty: "Easy", url: "https://leetcode.com/problems/climbing-stairs/", platform: "LeetCode" },
  { title: "Coin Change", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/coin-change/", platform: "LeetCode" },
  { title: "Longest Increasing Subsequence", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/longest-increasing-subsequence/", platform: "LeetCode" },
  { title: "Longest Common Subsequence", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/longest-common-subsequence/", platform: "LeetCode" },
  { title: "Word Break", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/word-break/", platform: "LeetCode" },
  { title: "Combination Sum IV", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/combination-sum-iv/", platform: "LeetCode" },
  { title: "House Robber", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/house-robber/", platform: "LeetCode" },
  { title: "House Robber II", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/house-robber-ii/", platform: "LeetCode" },
  { title: "Decode Ways", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/decode-ways/", platform: "LeetCode" },
  { title: "Unique Paths", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/unique-paths/", platform: "LeetCode" },
  { title: "Jump Game", topic: "DP", difficulty: "Medium", url: "https://leetcode.com/problems/jump-game/", platform: "LeetCode" },
  // Graph
  { title: "Clone Graph", topic: "Graph", difficulty: "Medium", url: "https://leetcode.com/problems/clone-graph/", platform: "LeetCode" },
  { title: "Course Schedule", topic: "Graph", difficulty: "Medium", url: "https://leetcode.com/problems/course-schedule/", platform: "LeetCode" },
  { title: "Pacific Atlantic Water Flow", topic: "Graph", difficulty: "Medium", url: "https://leetcode.com/problems/pacific-atlantic-water-flow/", platform: "LeetCode" },
  { title: "Number of Islands", topic: "Graph", difficulty: "Medium", url: "https://leetcode.com/problems/number-of-islands/", platform: "LeetCode" },
  { title: "Longest Consecutive Sequence", topic: "Graph", difficulty: "Medium", url: "https://leetcode.com/problems/longest-consecutive-sequence/", platform: "LeetCode" },
  { title: "Graph Valid Tree", topic: "Graph", difficulty: "Medium", url: "https://leetcode.com/problems/graph-valid-tree/", platform: "LeetCode" },
  // Interval
  { title: "Insert Interval", topic: "Interval", difficulty: "Medium", url: "https://leetcode.com/problems/insert-interval/", platform: "LeetCode" },
  { title: "Merge Intervals", topic: "Interval", difficulty: "Medium", url: "https://leetcode.com/problems/merge-intervals/", platform: "LeetCode" },
  { title: "Non-overlapping Intervals", topic: "Interval", difficulty: "Medium", url: "https://leetcode.com/problems/non-overlapping-intervals/", platform: "LeetCode" },
  { title: "Meeting Rooms", topic: "Interval", difficulty: "Easy", url: "https://leetcode.com/problems/meeting-rooms/", platform: "LeetCode" },
  { title: "Meeting Rooms II", topic: "Interval", difficulty: "Medium", url: "https://leetcode.com/problems/meeting-rooms-ii/", platform: "LeetCode" },
  // Linked List
  { title: "Reverse a Linked List", topic: "Linked List", difficulty: "Easy", url: "https://leetcode.com/problems/reverse-linked-list/", platform: "LeetCode" },
  { title: "Detect Cycle in a Linked List", topic: "Linked List", difficulty: "Easy", url: "https://leetcode.com/problems/linked-list-cycle/", platform: "LeetCode" },
  { title: "Merge Two Sorted Lists", topic: "Linked List", difficulty: "Easy", url: "https://leetcode.com/problems/merge-two-sorted-lists/", platform: "LeetCode" },
  { title: "Merge K Sorted Lists", topic: "Linked List", difficulty: "Hard", url: "https://leetcode.com/problems/merge-k-sorted-lists/", platform: "LeetCode" },
  { title: "Remove Nth Node From End Of List", topic: "Linked List", difficulty: "Medium", url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", platform: "LeetCode" },
  { title: "Reorder List", topic: "Linked List", difficulty: "Medium", url: "https://leetcode.com/problems/reorder-list/", platform: "LeetCode" },
  // Matrix
  { title: "Set Matrix Zeroes", topic: "Matrix", difficulty: "Medium", url: "https://leetcode.com/problems/set-matrix-zeroes/", platform: "LeetCode" },
  { title: "Spiral Matrix", topic: "Matrix", difficulty: "Medium", url: "https://leetcode.com/problems/spiral-matrix/", platform: "LeetCode" },
  { title: "Rotate Image", topic: "Matrix", difficulty: "Medium", url: "https://leetcode.com/problems/rotate-image/", platform: "LeetCode" },
  { title: "Word Search", topic: "Matrix", difficulty: "Medium", url: "https://leetcode.com/problems/word-search/", platform: "LeetCode" },
  // String
  { title: "Longest Substring Without Repeating Characters", topic: "String", difficulty: "Medium", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", platform: "LeetCode" },
  { title: "Longest Repeating Character Replacement", topic: "String", difficulty: "Medium", url: "https://leetcode.com/problems/longest-repeating-character-replacement/", platform: "LeetCode" },
  { title: "Minimum Window Substring", topic: "String", difficulty: "Hard", url: "https://leetcode.com/problems/minimum-window-substring/", platform: "LeetCode" },
  { title: "Valid Anagram", topic: "String", difficulty: "Easy", url: "https://leetcode.com/problems/valid-anagram/", platform: "LeetCode" },
  { title: "Group Anagrams", topic: "String", difficulty: "Medium", url: "https://leetcode.com/problems/group-anagrams/", platform: "LeetCode" },
  { title: "Valid Parentheses", topic: "String", difficulty: "Easy", url: "https://leetcode.com/problems/valid-parentheses/", platform: "LeetCode" },
  { title: "Valid Palindrome", topic: "String", difficulty: "Easy", url: "https://leetcode.com/problems/valid-palindrome/", platform: "LeetCode" },
  { title: "Longest Palindromic Substring", topic: "String", difficulty: "Medium", url: "https://leetcode.com/problems/longest-palindromic-substring/", platform: "LeetCode" },
  { title: "Palindromic Substrings", topic: "String", difficulty: "Medium", url: "https://leetcode.com/problems/palindromic-substrings/", platform: "LeetCode" },
  { title: "Encode and Decode Strings", topic: "String", difficulty: "Medium", url: "https://leetcode.com/problems/encode-and-decode-strings/", platform: "LeetCode" },
  // Tree
  { title: "Maximum Depth of Binary Tree", topic: "Tree", difficulty: "Easy", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", platform: "LeetCode" },
  { title: "Same Tree", topic: "Tree", difficulty: "Easy", url: "https://leetcode.com/problems/same-tree/", platform: "LeetCode" },
  { title: "Invert/Flip Binary Tree", topic: "Tree", difficulty: "Easy", url: "https://leetcode.com/problems/invert-binary-tree/", platform: "LeetCode" },
  { title: "Binary Tree Maximum Path Sum", topic: "Tree", difficulty: "Hard", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", platform: "LeetCode" },
  { title: "Binary Tree Level Order Traversal", topic: "Tree", difficulty: "Medium", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", platform: "LeetCode" },
  { title: "Serialize and Deserialize Binary Tree", topic: "Tree", difficulty: "Hard", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", platform: "LeetCode" },
  { title: "Subtree of Another Tree", topic: "Tree", difficulty: "Easy", url: "https://leetcode.com/problems/subtree-of-another-tree/", platform: "LeetCode" },
  { title: "Construct Binary Tree from Preorder and Inorder", topic: "Tree", difficulty: "Medium", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", platform: "LeetCode" },
  { title: "Validate Binary Search Tree", topic: "Tree", difficulty: "Medium", url: "https://leetcode.com/problems/validate-binary-search-tree/", platform: "LeetCode" },
  { title: "Kth Smallest Element in a BST", topic: "Tree", difficulty: "Medium", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", platform: "LeetCode" },
  { title: "Lowest Common Ancestor of BST", topic: "Tree", difficulty: "Easy", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", platform: "LeetCode" },
  { title: "Implement Trie (Prefix Tree)", topic: "Tree", difficulty: "Medium", url: "https://leetcode.com/problems/implement-trie-prefix-tree/", platform: "LeetCode" },
  { title: "Add and Search Word", topic: "Tree", difficulty: "Medium", url: "https://leetcode.com/problems/add-and-search-word-data-structure-design/", platform: "LeetCode" },
  { title: "Word Search II", topic: "Tree", difficulty: "Hard", url: "https://leetcode.com/problems/word-search-ii/", platform: "LeetCode" },
  // Heap
  { title: "Merge K Sorted Lists (Heap)", topic: "Heap", difficulty: "Hard", url: "https://leetcode.com/problems/merge-k-sorted-lists/", platform: "LeetCode" },
  { title: "Top K Frequent Elements", topic: "Heap", difficulty: "Medium", url: "https://leetcode.com/problems/top-k-frequent-elements/", platform: "LeetCode" },
  { title: "Find Median from Data Stream", topic: "Heap", difficulty: "Hard", url: "https://leetcode.com/problems/find-median-from-data-stream/", platform: "LeetCode" },
];

export const STARTER_SKILLS: Record<string, Array<{ name: string; category: string }>> = {
  "Software Engineering": [
    { name: "Data Structures & Algorithms", category: "technical" },
    { name: "System Design", category: "technical" },
    { name: "JavaScript / TypeScript", category: "technical" },
    { name: "React", category: "technical" },
    { name: "Node.js", category: "technical" },
    { name: "SQL", category: "technical" },
    { name: "Git", category: "tools" },
    { name: "Communication", category: "soft" },
  ],
  "Data Science / ML": [
    { name: "Python", category: "technical" },
    { name: "Statistics", category: "technical" },
    { name: "SQL", category: "technical" },
    { name: "Pandas / NumPy", category: "technical" },
    { name: "Machine Learning", category: "technical" },
    { name: "Deep Learning", category: "technical" },
    { name: "Data Storytelling", category: "soft" },
  ],
  "DevOps / Cloud": [
    { name: "Linux", category: "technical" },
    { name: "Docker", category: "tools" },
    { name: "Kubernetes", category: "tools" },
    { name: "AWS", category: "tools" },
    { name: "CI/CD", category: "technical" },
    { name: "Terraform", category: "tools" },
  ],
  "QA / Testing": [
    { name: "Manual Testing", category: "technical" },
    { name: "Selenium", category: "tools" },
    { name: "API Testing", category: "technical" },
    { name: "JIRA", category: "tools" },
    { name: "Test Case Design", category: "technical" },
  ],
  "Product / Analytics": [
    { name: "SQL", category: "technical" },
    { name: "Excel", category: "tools" },
    { name: "Tableau / PowerBI", category: "tools" },
    { name: "A/B Testing", category: "technical" },
    { name: "Product Sense", category: "soft" },
  ],
};

export const TARGET_DOMAINS = Object.keys(STARTER_SKILLS);
